# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendence',
            unique_together=set([('student', 'date')]),
        ),
    ]
